### ISSUE TITLE
Future releases planned?

### ISSUE THREAD

**Issue by nodesocket** [rethinkdb/rethinkdb-legacy#6698]
Curious if any future releases are planned? It's been over a year since the last release and wanted to see if progress is still continuing under the new leadership?

**Comment by 007lva** [comment]
Hi. Are you aware of "Rebirthdb"? Is a community fork that is close to release a 2.4.0 version (but without Windows support)

**Comment by withinboredom** [comment]
Looks like 2.4 changes there, are mostly rebranding and nothing useful?

**Comment by Extarys** [comment]
Thanks @007lva I didn't see that ! <3

**Comment by ChrisTalman** [comment]
Unfortunately there does not seem to be a 'new leadership'. There has been zero communication from those who theoretically have that role in this project.

**Comment by thelinuxlich** [comment]
You're wrong, Chris

**Comment by ChrisTalman** [comment]
Oh, cool. To clarify, essentially my only source for information about RethinkDB is this repository. I haven't followed any of the conversations within the Rebirth community in any depth. In that sense, I've observed 'zero communication', given that there has been essentially no official responses in this (RethinkDB) repository whenever people have raised concerns about the project.

In particular, I don't remember which issue it was, but there was one issue which received no official response, and within which people started discussing a fork and eventually went through with it in the form of Rebirth.

If the official leadership have started to communicate with you in some form, it would be nice if they and you could share that here. To an outside observer, there's not much we can glean about the situation.

**Comment by thelinuxlich** [comment]
Once everything is settled we will write a blog post with the words of the founders

**Comment by dhershman1** [comment]
> Once everything is settled we will write a blog post with the words of the founders

I hope this is coming up soon. The renaming of the repo to rethinkdb-legacy is worrysome. Though I am in the mind set this is because a new repo will emerge with rebirthdb merged into rethink

**Comment by atris** [comment]
The new rethinkdb repository is present already

**Comment by ghiscoding** [comment]
@thelinuxlich and everyone participants of RebirthDB fork

Isn't there a better way to merge `RebirthDB` in `RethinkDB` than current fork merge? I mean I was so damn surprised when I saw all opened issues were gone (leaving only RebirthDB issues opened) and all stars ⭐️  gone as well (previous `RebirthDB` 200 stars vs 21k stars on the new legacy name). 

I know it doesn't affect in any way the functionality of this project but it might turn away some people when they see all issues/stars gone (at first perception). I know it's all there but it's so hidden that I was quite confused at first (even though you might write a blog post about it, not everyone will read it).

This is just my personal view, I know you are doing what is best for this project to live on :)

**Comment by thelinuxlich** [comment]
@ghiscoding there was a long discussion with the actual core team and we agreed to make this move because although some issues are very useful information-wise(and that's why we are keeping the legacy repo), RethinkDB is production-ready and we should restart on a clean slate to have focus. 
We believe that, once we make some noise in scene with the new release, we might regain steam with a renewed community :)

**Comment by ricardobeat** [comment]
Not seeing any steam in the repositories. There have been nearly zero useful commits during the entire 2018 (besides the move to Duktape). Saying the new fork is not production ready certainly does not help - seems like this fork managed to kill both sides of the project. Is something being developed in private?

**Comment by jonathandays** [comment]
Please guys! I love rethinkdb! I hope this does not stop. There is no other db that is so easy to use!  :'(

**Comment by thelinuxlich** [comment]
@ricardobeat why don't you do a diff and see for yourself? It's cheap to complain, but to collaborate...

@jonathandays We love RethinkDB as much as you do, but we are lacking strength in core development, thus the stagnation :(

**Comment by ricardobeat** [comment]
@thelinuxlich sorry you feel offended. I'm looking at the commit history for rethinkdb/rethinkdb-legacy and rethinkdb/rethinkdb, e.g https://github.com/rethinkdb/rethinkdb/pulse/monthly. I have to say that response is not exactly collaboration-inspiring either.

My point is maybe this decision should be reconsidered, and both repos brought together again? Updates will reach 20k+ more people, and any potential contributors will have a good pile of open issues to get started. I actually appreciate the change to Duktape as it reduces complexity and build cost a lot, but couldn't find any mention of a roadmap or near/long-term goals for the fork.

**Comment by jonathandays** [comment]
@thelinuxlich  I am very grateful for all the work you guys put in. I am trying to be a better developer to see how i could help you guys! Not much experience in contributing to open source. If i could do something in python(only language i currently develop) i would gladly try to help! Not sure where to begin!

**Comment by thelinuxlich** [comment]
@ricardobeat here are the tasks remaining for a 2.4 release:

https://spectrum.chat/rethinkdb/questions/is-there-an-eta-for-release~be358119-9017-447d-9b4e-592a0d285248?m=MTUzOTE3NzAzNzU0Ng==

You'll see your suggestion is already there.

**Comment by ChrisTalman** [comment]
>  I have to say that response is not exactly collaboration-inspiring either.

It's really useful to draw attention to this matter. Friendly communication is very important for open source projects. Unfortunately, a lot of projects overlook this, which lead to many unpleasant exchanges where one or more parties walk away unhappy. That's not cool, and not conducive to growing a project. I think this project under the company handled its communication really well, both here and in other forums. Even if there's little development progress right now, it would be good for us to all aspire to maintain this project's tradition of friendly communication.

**Comment by thelinuxlich** [comment]
Closing this one and quoting Linus Torvalds:

"Talk is cheap, show me the code."
