### ISSUE TITLE
Cannot wrap undefined with r.expr()

### ISSUE THREAD

**Issue by Leen15** [rethinkdb/rethinkdb-legacy#6707]
Hi,
I'm trying to create a compound index with this command:
`r.db('versioning').table("model_histories").indexCreate(
    "model_and_object", [r.row["model_name"], r.row["object_id"]]
).run(conn)`

But I receive the follow error:
`Cannot wrap undefined with r.expr()`

I'm running the command from the "Data Explorer" page in UI.

What could be the issue?

Also, in all docs the function to use should be `index_create` but I receive an error if I try to use it:
`r.table(...).index_create is not a function`

Thanks

**Comment by ronzeidman** [comment]
looks like you've seen docs in python when you use js... It probably should be:
```js
r.db('versioning').table("model_histories").indexCreate( "model_and_object", [r.row("model_name"), r.row("object_id")] ).run(conn)
```
indexCreate (js): https://rethinkdb.com/api/javascript/index_create/
index_create (python): https://rethinkdb.com/api/python/index_create/

**Comment by Leen15** [comment]
Thanks, yes maybe some misunderstanding with the doc ;)
